language: python
python:
  #- "2.6"
  - "2.7"
  #- "pypy"

notifications:
  email:
    - keith@parsely.com

before_install:
    - sudo apt-get install -qq libev-dev libsnappy-dev
    #- sudo apt-get install -qq zookeeper libev-dev libsnappy-dev
    #- make -C vendor kafka > /dev/null
    #- sudo mv vendor/kafka /usr/local/kafka

install:
    - python setup.py develop
    - pip install --use-mirrors pykafka[test]

env: ZOOKEEPER_PATH=/usr/share/java KAFKA_PATH=/usr/local/kafka KAFKA_START_TIMEOUT=30

script: make test
