language: python
python:
  - "2.7"

notifications:
  email:
    - keith@parsely.com
    - emmett@parsely.com

before_install:
    - sudo apt-get install -qq libev-dev libsnappy-dev

cache:
    directories:
        # Cache venv
        - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages

install:
    - pip install python-snappy kazoo
    - python setup.py develop

branches:
  only:
    - master

script: make test
