language: python
python:
  #- "2.6"
  - "2.7"
  #- "pypy"

notifications:
  email:
    - keith@parsely.com

before_install:
    - sudo apt-get install -qq libev-dev libsnappy-dev

install:
    - pip install python-snappy kazoo
    - python setup.py develop

env: ZOOKEEPER_PATH=/usr/share/java KAFKA_PATH=/usr/local/kafka KAFKA_START_TIMEOUT=30

script: make test
