language: python
python:
  - "2.7"

env:
  - BROKERS=localhost:9092,localhost:9093,localhost:9094 ZOOKEEPER=localhost:2181 KAFKA_BIN=/home/travis/kafka-bin

notifications:
  email:
    - keith@parsely.com
    - emmett@parsely.com

before_install:
    - sudo apt-get install -qq libev-dev libsnappy-dev

install:
    - pip install python-snappy kazoo
    - pip install testinstances
    - python setup.py develop

before_script:
    - "python -m pykafka.test.kafka_instance 3 --download-dir /home/travis/kafka-bin &"
    - "sleep 10"

branches:
  only:
    - master

script: make test
