language: python
python:
  - "2.6"
  - "2.7"

notifications:
  email:
    - mwhooker@disqus.com
    - ted@disqus.com
  irc: "irc.freenode.org#samsa"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq zookeeper libev-dev
    - export KAFKA_VERSION=0.7.1-incubating
    - export KAFKA_URL=http://mirrors.sonic.net/apache/incubator/kafka/kafka-${KAFKA_VERSION}/kafka-${KAFKA_VERSION}-src.tgz
    - export SRC_TGZ=$(basename $KAFKA_URL)
    - export TEMP=$(mktemp -d)
    - pushd ${TEMP}
    - sudo curl -O $KAFKA_URL
    - tar xzf ${SRC_TGZ}
    - pushd kafka-${KAFKA_VERSION}
    - ./sbt update
    - ./sbt package
    - popd
    - sudo mv kafka-${KAFKA_VERSION} /usr/local/kafka
    - popd

install:
    - pip install -f http://code.google.com/p/gevent/downloads/list gevent>1.0dev >/dev/null 2>&1
    - pip install "git+https://github.com/python-zk/kazoo.git"
    - pip install --use-mirrors zc-zookeeper-static >/dev/null 2>&1
    - python setup.py develop
    - pip install --use-mirrors samsa[test]

env: ZOOKEEPER_PATH=/usr/share/java KAFKA_PATH=/usr/local/kafka

script: make test
