language: python
python:
  #- "2.6"
  - "2.7"
  #- "pypy"

notifications:
  email:
    - keith@parsely.com
    - emmett@parsely.com

before_install:
    - sudo apt-get install -qq libev-dev libsnappy-dev
    - sudo apt-get install -qq zlib1g-dev  # for librdkafka
    - wget https://github.com/edenhill/librdkafka/archive/0.8.6.tar.gz
    - tar -xzf 0.8.6.tar.gz
    - cd librdkafka-0.8.6/ && ./configure && make && sudo make install && cd -

install:
    - pip install python-snappy kazoo
    - python setup.py develop

env: ZOOKEEPER_PATH=/usr/share/java KAFKA_PATH=/usr/local/kafka KAFKA_START_TIMEOUT=30

script: make test
